/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SwingDBTable;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.RowFilter;
import javax.swing.Timer;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author alper
 */
public class mainFrame extends javax.swing.JFrame {

    DefaultTableModel tableModel;
    CityManager cityManager = new CityManager();
    Timer timer;
    
    public mainFrame() {
        initComponents();
        tableModel = (DefaultTableModel) tblCities.getModel();
        restartList();
    }
    public final void restartList(){
        ArrayList<Citys> cities = cityManager.getCities();
        tableListCities(cities);
    }

    public final void tableListCities(ArrayList<Citys> cities) {
        tableModel.setRowCount(0);
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        renderer.setHorizontalAlignment(DefaultTableCellRenderer.LEFT);
        tblCities.getColumnModel().getColumn(0).setCellRenderer(renderer);
        tblCities.getColumnModel().getColumn(1).setCellRenderer(renderer);
        tblCities.getColumnModel().getColumn(2).setCellRenderer(renderer);
        for (Citys city : cities) {
            Object[] row = {city.getCity_id(), city.getCity_name(),
                city.getCountry_id()};
            tableModel.addRow(row);
        }
    }

    public final void timer(int time) {
        this.timer = new Timer(time * 1000, actionEvent -> warningLabel.setText(""));
        timer.setRepeats(false);
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jFrame3 = new javax.swing.JFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCities = new javax.swing.JTable();
        cityNameText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cityIDText1 = new javax.swing.JTextField();
        filterButton2 = new javax.swing.JButton();
        warningLabelName = new javax.swing.JLabel();
        warningLabelID = new javax.swing.JLabel();
        warningLabelText = new javax.swing.JLabel();
        warningLabel = new javax.swing.JLabel();
        deleteCityButton = new javax.swing.JButton();
        addCityButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame3Layout = new javax.swing.GroupLayout(jFrame3.getContentPane());
        jFrame3.getContentPane().setLayout(jFrame3Layout);
        jFrame3Layout.setHorizontalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame3Layout.setVerticalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(50, 70));
        setMinimumSize(new java.awt.Dimension(478, 369));
        setPreferredSize(new java.awt.Dimension(479, 370));
        setResizable(false);
        getContentPane().setLayout(null);

        tblCities.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "City ID", "City Name", "Country ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblCities);
        if (tblCities.getColumnModel().getColumnCount() > 0) {
            tblCities.getColumnModel().getColumn(0).setMinWidth(100);
            tblCities.getColumnModel().getColumn(0).setPreferredWidth(100);
            tblCities.getColumnModel().getColumn(0).setMaxWidth(100);
            tblCities.getColumnModel().getColumn(1).setMinWidth(255);
            tblCities.getColumnModel().getColumn(1).setPreferredWidth(255);
            tblCities.getColumnModel().getColumn(1).setMaxWidth(255);
            tblCities.getColumnModel().getColumn(2).setMinWidth(80);
            tblCities.getColumnModel().getColumn(2).setPreferredWidth(80);
            tblCities.getColumnModel().getColumn(2).setMaxWidth(80);
        }

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(6, 61, 452, 210);

        cityNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityNameTextActionPerformed(evt);
            }
        });
        cityNameText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cityNameTextKeyReleased(evt);
            }
        });
        getContentPane().add(cityNameText);
        cityNameText.setBounds(161, 6, 178, 22);

        jLabel2.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        jLabel2.setText("Search City Name:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(39, 6, 110, 23);

        jLabel4.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        jLabel4.setText("Country ID:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(78, 37, 71, 15);

        cityIDText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityIDText1ActionPerformed(evt);
            }
        });
        cityIDText1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cityIDText1KeyReleased(evt);
            }
        });
        getContentPane().add(cityIDText1);
        cityIDText1.setBounds(161, 33, 49, 22);

        filterButton2.setFont(new java.awt.Font("Segoe UI Historic", 0, 10)); // NOI18N
        filterButton2.setText("Search Country ID");
        filterButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        filterButton2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        filterButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(filterButton2);
        filterButton2.setBounds(222, 35, 113, 20);

        warningLabelName.setBackground(new java.awt.Color(255, 153, 153));
        warningLabelName.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        getContentPane().add(warningLabelName);
        warningLabelName.setBounds(668, 216, 0, 0);

        warningLabelID.setFont(new java.awt.Font("Segoe UI Historic", 2, 14)); // NOI18N
        getContentPane().add(warningLabelID);
        warningLabelID.setBounds(464, 214, 0, 0);

        warningLabelText.setFont(new java.awt.Font("Segoe UI Historic", 2, 14)); // NOI18N
        getContentPane().add(warningLabelText);
        warningLabelText.setBounds(668, 216, 0, 0);

        warningLabel.setFont(new java.awt.Font("Segoe UI Historic", 2, 14)); // NOI18N
        getContentPane().add(warningLabel);
        warningLabel.setBounds(470, 222, 114, 0);

        deleteCityButton.setBackground(new java.awt.Color(255, 153, 153));
        deleteCityButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        deleteCityButton.setText("DELETE CITY");
        deleteCityButton.setBorder(null);
        deleteCityButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteCityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCityButtonActionPerformed(evt);
            }
        });
        getContentPane().add(deleteCityButton);
        deleteCityButton.setBounds(28, 283, 90, 34);

        addCityButton.setBackground(new java.awt.Color(153, 255, 153));
        addCityButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        addCityButton.setText("ADD CITY");
        addCityButton.setBorder(null);
        addCityButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addCityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCityButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addCityButton);
        addCityButton.setBounds(146, 283, 90, 34);

        refreshButton.setBackground(new java.awt.Color(255, 255, 102));
        refreshButton.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        refreshButton.setText("REFRESH");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });
        getContentPane().add(refreshButton);
        refreshButton.setBounds(359, 283, 90, 35);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cityNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityNameTextActionPerformed

    private void cityIDText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityIDText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityIDText1ActionPerformed

    private void filterButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterButton2ActionPerformed
        ArrayList<Citys> cities;
        if (cityIDText1.getText().isEmpty()) {
            restartList();
            return;
        }
        cities = cityManager.citiesFilterCountryID(cityIDText1.getText());
        try {
            tableListCities(cities);
        } catch (NullPointerException ex) {
            warningLabel.setText("ID not found...");
            timer(4);
            restartList();
        }
    }//GEN-LAST:event_filterButton2ActionPerformed

    private void addCityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCityButtonActionPerformed
        AddCityForm addCityForm = new AddCityForm();
        addCityForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        addCityForm.setVisible(true);
    }//GEN-LAST:event_addCityButtonActionPerformed

    private void deleteCityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCityButtonActionPerformed
        DeleteCityForm deleteCityForm = new DeleteCityForm();
        deleteCityForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        deleteCityForm.setVisible(true);
    }//GEN-LAST:event_deleteCityButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        restartList();
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void cityNameTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cityNameTextKeyReleased
        String search = cityNameText.getText();
        TableRowSorter<DefaultTableModel> tableRowSorterName = new TableRowSorter<DefaultTableModel>(tableModel);
        tblCities.setRowSorter(tableRowSorterName);
        tableRowSorterName.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_cityNameTextKeyReleased

    private void cityIDText1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cityIDText1KeyReleased
        
    }//GEN-LAST:event_cityIDText1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCityButton;
    private javax.swing.JTextField cityIDText1;
    private javax.swing.JTextField cityNameText;
    private javax.swing.JButton deleteCityButton;
    private javax.swing.JButton filterButton2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton refreshButton;
    private javax.swing.JTable tblCities;
    private javax.swing.JLabel warningLabel;
    private javax.swing.JLabel warningLabelID;
    private javax.swing.JLabel warningLabelName;
    private javax.swing.JLabel warningLabelText;
    // End of variables declaration//GEN-END:variables
}
